import type { DJ, TicketTier, GalleryEdition, Excursion } from './data';

export const DEFAULT_LINEUP: DJ[] = [
  {
    id: 'wisllow',
    name: 'WISLLOW',
    genre: 'PROGRESSIVE',
    time: '',
    img: './wisllow.jpeg',
    position: 'object-top',
    scUrl: 'https://soundcloud.com/wisllowmusic/wisllow-takitahoriginal-mix-ubuntu-records',
    instagramUrl: 'https://www.instagram.com/wisllowmusic/',
    isConfirmed: true,
  },{
    id: 'Anjuna',
    name: 'ANJUNA',
    genre: 'GOA',
    time: '',
    img: './anjuna.png',
    position: 'object-top',
    scUrl: 'https://soundcloud.com/neotropicah/omeyocan-full-set-goanitzhogoa?si=67fa743eb3bd4e7caa16db54c26c6fae&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing',
    instagramUrl: 'https://www.instagram.com/goa.anjuna/',
    isConfirmed: true,
  },{
    id: 'Dopamina',
    name: 'DOPAMINA',
    genre: 'PROGRESSIVE',
    time: '',
    img: './dopamina.jpeg',
    position: 'object-top',
    scUrl: 'https://soundcloud.com/dopaminamusic/dopamina-beth-groove?si=8849e62260ea47278d5255417148e3c3&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing',
    instagramUrl: 'https://www.instagram.com/dopaminadj/',
    isConfirmed: true,
  }

];

export const DEFAULT_TICKETS: TicketTier[] = [
  {
    id: 'tier2',
    title: '1º Lote',
    subtitle: 'Meia entrada',
    price: 'R$ 50',
    status: 'LOTE ATUAL',
    features: ['Acesso aos 2 dias de evento', 'Área de Camping Standard', 'Água free no Chillout'],
    link: 'https://app.hi.events/event/7241/odysseia-o-exilir-de-calypso',
    highlighted: true,
    isActive: true,
  },{
    id: 'tier1',
    title: '1º Lote ',
    subtitle: 'Inteira',
    price: 'R$ 100',
    status: 'LOTE ATUAL',
    features: [],
    link: 'https://app.hi.events/event/7241/odysseia-o-exilir-de-calypso',
    highlighted: true,
    isActive: true,
  },  
 
];

export const DEFAULT_GALLERY: GalleryEdition[] = [
  {
    id: 'ed1',
    title: 'Odysseia Prólogo',
    year: '2024.1',
    cover: './1.png',
    googlePhotosUrl: 'https://drive.google.com/drive/folders/1D5RBWPeQcf8zO4LYsVoINWDsqbvBK3Lq?usp=sharing',
    
  },
  {
    id: 'ed2',
    title: 'Ilha de Lotófagos ',
    year: '2024.2',
    cover: './2.png',
    googlePhotosUrl: 'https://drive.google.com/drive/folders/1pAI60rlyoFKbCyRwjbqJr5AfZPvAkzyB?usp=sharing',
   
  },
  {
    id: 'ed3',
    title: 'O Canto das Sereias',
    year: '2025.1',
    cover: './3.png',
    googlePhotosUrl: 'https://drive.google.com/drive/folders/1aolGG0NduKxTLioOds9u7G6epa0S0DgF?usp=sharing',
    
  },
  {
    id: 'ed4',
    title: 'O Guardião dos Ventos',
    year: '2025.2',
    cover: './4.png',
    googlePhotosUrl: 'https://drive.google.com/drive/folders/1rzjGpYfoFJEi3q1gFfPNUKByKpOk6kWx?usp=sharing',
   
  },
];

export const DEFAULT_EXCURSIONS: Excursion[] = [
  {
    id: '1',
    city: 'Santo Antonio de Jesus',
    excursionName: 'Santo Antonio de Jesus',
    state: 'BA',
    status: 'VAGAS LIMITADAS',
    departureTime: 'A definir',
    location: 'Praça Padre Matheus',
    contactName: 'Silas Yan',
    contactInstagram: 'https://www.instagram.com/itsyan_z/',
    whatsappNumber: '75988725232',
    isActive: true,
  },
  {
    id: '2',
    city: 'Cruz das Almas',
    excursionName: 'Cruz das Almas',
    state: 'BA',
    status: 'DISPONÍVEL',
    departureTime: 'A definir',
    location: 'Rodoviária de Cruz das Almas e Praça da Master',
    contactName: 'Viny Patrick',
    contactInstagram: 'https://www.instagram.com/vinypatrick/',
    whatsappNumber: '73991030905',
    isActive: true,
  },
  {
    id: '3',
    city: 'Vitória da Conquista',
    excursionName: 'Gnomland',
    state: 'BA',
    status: 'VAGAS LIMITADAS',
    departureTime: 'A definir',
    location: 'A definir',
    contactName: 'Gnomland',
    contactInstagram: 'https://www.instagram.com/gnomland077/',
    whatsappNumber: '77988769212',
    isActive: true,
  },
  {
    id: '4',
    city: 'Simões Filho',
    excursionName: 'Psy Birds',
    state: 'BA',
    status: 'VAGAS LIMITADAS',
    departureTime: 'A definir',
    location: 'Cia 1',
    contactName: 'Leo Schullz',
    contactInstagram: 'https://www.instagram.com/psy.birds/',
    whatsappNumber: '71988908768',
    isActive: true,
  },
  {
    id: '5',
    city: 'Itacaré',
    excursionName: 'Fritos no Dendê',
    state: 'BA',
    status: 'VAGAS LIMITADAS',
    departureTime: 'A definir',
    location: 'A definir',
    contactName: 'Jon e Carlos',
    contactInstagram: 'https://www.instagram.com/fritosnodende/',
    whatsappNumber: '73999155132',
    isActive: true,
  },
  {
    id: '6',
    city: 'Itabuna / Ilhéus / Ubaitaba',
    excursionName: 'Os Villers',
    state: 'BA',
    status: 'VAGAS LIMITADAS',
    departureTime: 'A definir',
    location: 'A definir',
    contactName: 'Feh Matthos',
    contactInstagram: 'https://www.instagram.com/0svillers/',
    whatsappNumber: '71996946995',
    isActive: true,
  },
  {
    id: '7',
    city: 'Feira de Santana',
    excursionName: 'Nave075',
    state: 'BA',
    status: 'VAGAS LIMITADAS',
    departureTime: 'A definir',
    location: 'Praça de alimentação (próximo ao Limão Drinks)',
    contactName: 'Aline e Monalisa',
    contactInstagram: 'https://www.instagram.com/bvnave075/',
    whatsappNumber: '75981900935',
    isActive: true,
  },{
    id: '8',
    city: 'Camaçari',
    excursionName: '',
    state: 'BA',
    status: 'VAGAS LIMITADAS',
    departureTime: 'A definir',
    location: 'Camaçari e Orla de Camaro ',
    contactName: 'Ericson Lima',
    contactInstagram: 'https://www.instagram.com/eric.limx99/',
    whatsappNumber: '71982808712',
    isActive: true,
  },{
    id: '9',
    city: 'Ipiaú',
    excursionName: 'Terra de Insannos 73',
    state: 'BA',
    status: 'VAGAS LIMITADAS',
    departureTime: 'A definir',
    location: 'Jequié, Ipiaú ',
    contactName: 'Fagner',
    contactInstagram: 'https://www.instagram.com/terra_de_insannos73/',
    whatsappNumber: '73981959175',
    isActive: true,
  },{
    id: '10',
    city: 'Salvador',
    excursionName: 'Expresso071',
    state: 'BA',
    status: 'VAGAS LIMITADAS',
    departureTime: 'A definir',
    location: 'Hiperposto',
    contactName: 'Alpha Taxi',
    contactInstagram: 'https://www.instagram.com/expresso.071/',
    whatsappNumber: '71991282042',
    isActive: true,
  },{
    id: '11',
    city: 'Petrolina',
    excursionName: 'Vale Trips',
    state: 'PE',
    status: 'VAGAS LIMITADAS',
    departureTime: 'A definir',
    location: 'Hiperposto',
    contactName: 'Luan Jonathan',
    contactInstagram: 'https://www.instagram.com/valetrips874/',
    whatsappNumber: '87981289766',
    isActive: true,
  }
  
];
